---
abstract: "convert flat hash to nested data using TT2's dot convention"
author:
  - 'Brad Bowman <cgi-expand@bereft.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Expand
no_index:
  directory:
    - t
    - inc
requires:
  Test::Exception: 0
  Test::More: 0
version: 2.04
